import type { Restaurant, MenuItem, Customer, Order, DeliveryPerson } from "./types"

export const mockRestaurants: Restaurant[] = [
  {
    restaurant_id: 1,
    name: "Spice Garden",
    location: "Sector 17, Chandigarh",
    rating: 4.5,
    cuisine: "Indian",
    image: "/indian-restaurant-food.png",
  },
  {
    restaurant_id: 2,
    name: "Pizza Paradise",
    location: "Sector 35, Chandigarh",
    rating: 4.7,
    cuisine: "Italian",
    image: "/bustling-pizza-restaurant.png",
  },
  {
    restaurant_id: 3,
    name: "Sushi Master",
    location: "Sector 26, Chandigarh",
    rating: 4.8,
    cuisine: "Japanese",
    image: "/bustling-sushi-restaurant.png",
  },
  {
    restaurant_id: 4,
    name: "Burger House",
    location: "Sector 22, Chandigarh",
    rating: 4.3,
    cuisine: "American",
    image: "/burger-restaurant.png",
  },
  {
    restaurant_id: 5,
    name: "Thai Delight",
    location: "Sector 9, Chandigarh",
    rating: 4.6,
    cuisine: "Thai",
    image: "/thai-restaurant.png",
  },
  {
    restaurant_id: 6,
    name: "Taco Fiesta",
    location: "Sector 8, Chandigarh",
    rating: 4.4,
    cuisine: "Mexican",
    image: "/vibrant-mexican-tacos.png",
  },
  {
    restaurant_id: 7,
    name: "Dosa Corner",
    location: "Sector 43, Chandigarh",
    rating: 4.6,
    cuisine: "South Indian",
    image: "/south-indian-dosa.jpg",
  },
  {
    restaurant_id: 8,
    name: "Dragon Wok",
    location: "Sector 11, Chandigarh",
    rating: 4.5,
    cuisine: "Chinese",
    image: "/chinese-restaurant.jpg",
  },
  {
    restaurant_id: 9,
    name: "Cafe Mocha",
    location: "Sector 7, Chandigarh",
    rating: 4.7,
    cuisine: "Cafe",
    image: "/cozy-cafe.jpg",
  },
  {
    restaurant_id: 10,
    name: "The Grill House",
    location: "Sector 28, Chandigarh",
    rating: 4.4,
    cuisine: "BBQ",
    image: "/bbq-grill.jpg",
  },
  {
    restaurant_id: 11,
    name: "Sweet Treats Bakery",
    location: "Sector 19, Chandigarh",
    rating: 4.8,
    cuisine: "Bakery",
    image: "/bakery-shop.jpg",
  },
  {
    restaurant_id: 12,
    name: "Mediterranean Delight",
    location: "Sector 34, Chandigarh",
    rating: 4.6,
    cuisine: "Mediterranean",
    image: "/mediterranean-food.jpg",
  },
]

export const mockMenuItems: MenuItem[] = [
  // Spice Garden (Indian)
  {
    item_id: 1,
    restaurant_id: 1,
    name: "Butter Chicken",
    price: 320,
    description: "Creamy tomato curry with tender chicken",
    image: "/butter-chicken.png",
    category: "Main Course",
  },
  {
    item_id: 2,
    restaurant_id: 1,
    name: "Paneer Tikka",
    price: 280,
    description: "Grilled cottage cheese with spices",
    image: "/paneer-tikka.png",
    category: "Appetizer",
  },
  {
    item_id: 3,
    restaurant_id: 1,
    name: "Biryani",
    price: 350,
    description: "Fragrant rice with spiced meat",
    image: "/flavorful-biryani.png",
    category: "Main Course",
  },
  {
    item_id: 4,
    restaurant_id: 1,
    name: "Naan Bread",
    price: 50,
    description: "Fresh baked flatbread",
    image: "/naan-bread.png",
    category: "Sides",
  },

  // Pizza Paradise (Italian)
  {
    item_id: 5,
    restaurant_id: 2,
    name: "Margherita Pizza",
    price: 299,
    description: "Classic tomato, mozzarella, and basil",
    image: "/margherita-pizza.png",
    category: "Pizza",
  },
  {
    item_id: 6,
    restaurant_id: 2,
    name: "Pepperoni Pizza",
    price: 399,
    description: "Loaded with pepperoni and cheese",
    image: "/pepperoni-pizza.png",
    category: "Pizza",
  },
  {
    item_id: 7,
    restaurant_id: 2,
    name: "Caesar Salad",
    price: 180,
    description: "Crisp romaine with parmesan",
    image: "/caesar-salad.png",
    category: "Salad",
  },
  {
    item_id: 8,
    restaurant_id: 2,
    name: "Tiramisu",
    price: 150,
    description: "Classic Italian dessert",
    image: "/classic-tiramisu.png",
    category: "Dessert",
  },

  // Sushi Master (Japanese)
  {
    item_id: 9,
    restaurant_id: 3,
    name: "California Roll",
    price: 450,
    description: "Crab, avocado, and cucumber",
    image: "/california-roll.png",
    category: "Rolls",
  },
  {
    item_id: 10,
    restaurant_id: 3,
    name: "Salmon Nigiri",
    price: 550,
    description: "Fresh salmon over rice",
    image: "/salmon-nigiri.png",
    category: "Nigiri",
  },
  {
    item_id: 11,
    restaurant_id: 3,
    name: "Miso Soup",
    price: 120,
    description: "Traditional soybean soup",
    image: "/miso-soup.png",
    category: "Soup",
  },
  {
    item_id: 12,
    restaurant_id: 3,
    name: "Edamame",
    price: 140,
    description: "Steamed soybeans with sea salt",
    image: "/edamame-bowl.png",
    category: "Appetizer",
  },

  // Burger House (American)
  {
    item_id: 13,
    restaurant_id: 4,
    name: "Classic Burger",
    price: 220,
    description: "Beef patty with lettuce and tomato",
    image: "/classic-burger.png",
    category: "Burgers",
  },
  {
    item_id: 14,
    restaurant_id: 4,
    name: "Cheese Burger",
    price: 250,
    description: "With melted cheddar cheese",
    image: "/classic-cheeseburger.png",
    category: "Burgers",
  },
  {
    item_id: 15,
    restaurant_id: 4,
    name: "French Fries",
    price: 99,
    description: "Crispy golden fries",
    image: "/crispy-french-fries.png",
    category: "Sides",
  },
  {
    item_id: 16,
    restaurant_id: 4,
    name: "Milkshake",
    price: 120,
    description: "Creamy vanilla milkshake",
    image: "/classic-milkshake.png",
    category: "Drinks",
  },

  // Thai Delight (Thai)
  {
    item_id: 17,
    restaurant_id: 5,
    name: "Pad Thai",
    price: 280,
    description: "Stir-fried rice noodles",
    image: "/pad-thai.png",
    category: "Noodles",
  },
  {
    item_id: 18,
    restaurant_id: 5,
    name: "Green Curry",
    price: 320,
    description: "Spicy coconut curry",
    image: "/green-curry.png",
    category: "Curry",
  },
  {
    item_id: 19,
    restaurant_id: 5,
    name: "Spring Rolls",
    price: 150,
    description: "Fresh vegetable rolls",
    image: "/fresh-spring-rolls.png",
    category: "Appetizer",
  },
  {
    item_id: 20,
    restaurant_id: 5,
    name: "Mango Sticky Rice",
    price: 160,
    description: "Sweet coconut rice with mango",
    image: "/mango-sticky-rice.jpg",
    category: "Dessert",
  },

  // Taco Fiesta (Mexican)
  {
    item_id: 21,
    restaurant_id: 6,
    name: "Beef Tacos",
    price: 199,
    description: "Three soft tacos with seasoned beef",
    image: "/beef-tacos.jpg",
    category: "Tacos",
  },
  {
    item_id: 22,
    restaurant_id: 6,
    name: "Chicken Burrito",
    price: 260,
    description: "Large burrito with grilled chicken",
    image: "/chicken-burrito.png",
    category: "Burritos",
  },
  {
    item_id: 23,
    restaurant_id: 6,
    name: "Guacamole & Chips",
    price: 170,
    description: "Fresh guacamole with tortilla chips",
    image: "/guacamole-and-chips.png",
    category: "Appetizer",
  },
  {
    item_id: 24,
    restaurant_id: 6,
    name: "Churros",
    price: 130,
    description: "Fried dough with cinnamon sugar",
    image: "/churros.jpg",
    category: "Dessert",
  },

  // Dosa Corner (South Indian) - Restaurant 7
  {
    item_id: 25,
    restaurant_id: 7,
    name: "Masala Dosa",
    price: 120,
    description: "Crispy rice crepe with spiced potato filling",
    image: "/masala-dosa.jpg",
    category: "Main Course",
  },
  {
    item_id: 26,
    restaurant_id: 7,
    name: "Idli Sambar",
    price: 80,
    description: "Steamed rice cakes with lentil soup",
    image: "/idli-sambar.jpg",
    category: "Main Course",
  },
  {
    item_id: 27,
    restaurant_id: 7,
    name: "Vada",
    price: 60,
    description: "Crispy lentil fritters",
    image: "/medu-vada.jpg",
    category: "Appetizer",
  },
  {
    item_id: 28,
    restaurant_id: 7,
    name: "Filter Coffee",
    price: 50,
    description: "Traditional South Indian coffee",
    image: "/filter-coffee.jpg",
    category: "Drinks",
  },

  // Dragon Wok (Chinese) - Restaurant 8
  {
    item_id: 29,
    restaurant_id: 8,
    name: "Hakka Noodles",
    price: 180,
    description: "Stir-fried noodles with vegetables",
    image: "/hakka-noodles.jpg",
    category: "Noodles",
  },
  {
    item_id: 30,
    restaurant_id: 8,
    name: "Manchurian",
    price: 220,
    description: "Fried vegetable balls in spicy sauce",
    image: "/manchurian.jpg",
    category: "Main Course",
  },
  {
    item_id: 31,
    restaurant_id: 8,
    name: "Fried Rice",
    price: 160,
    description: "Wok-tossed rice with vegetables",
    image: "/fried-rice.jpg",
    category: "Rice",
  },
  {
    item_id: 32,
    restaurant_id: 8,
    name: "Spring Rolls",
    price: 140,
    description: "Crispy vegetable rolls",
    image: "/chinese-spring-rolls.jpg",
    category: "Appetizer",
  },

  // Cafe Mocha (Cafe) - Restaurant 9
  {
    item_id: 33,
    restaurant_id: 9,
    name: "Cappuccino",
    price: 120,
    description: "Espresso with steamed milk foam",
    image: "/cappuccino.jpg",
    category: "Drinks",
  },
  {
    item_id: 34,
    restaurant_id: 9,
    name: "Chocolate Brownie",
    price: 150,
    description: "Rich chocolate brownie with ice cream",
    image: "/chocolate-brownie.jpg",
    category: "Dessert",
  },
  {
    item_id: 35,
    restaurant_id: 9,
    name: "Club Sandwich",
    price: 200,
    description: "Triple-decker sandwich with chicken",
    image: "/club-sandwich.jpg",
    category: "Sandwiches",
  },
  {
    item_id: 36,
    restaurant_id: 9,
    name: "Pasta Alfredo",
    price: 280,
    description: "Creamy white sauce pasta",
    image: "/pasta-alfredo.jpg",
    category: "Main Course",
  },

  // The Grill House (BBQ) - Restaurant 10
  {
    item_id: 37,
    restaurant_id: 10,
    name: "BBQ Chicken Wings",
    price: 320,
    description: "Smoky grilled chicken wings",
    image: "/bbq-wings.jpg",
    category: "Appetizer",
  },
  {
    item_id: 38,
    restaurant_id: 10,
    name: "Grilled Steak",
    price: 550,
    description: "Juicy grilled beef steak",
    image: "/grilled-steak.jpg",
    category: "Main Course",
  },
  {
    item_id: 39,
    restaurant_id: 10,
    name: "BBQ Ribs",
    price: 480,
    description: "Tender pork ribs with BBQ sauce",
    image: "/bbq-ribs.jpg",
    category: "Main Course",
  },
  {
    item_id: 40,
    restaurant_id: 10,
    name: "Corn on the Cob",
    price: 80,
    description: "Grilled corn with butter",
    image: "/grilled-corn.jpg",
    category: "Sides",
  },

  // Sweet Treats Bakery (Bakery) - Restaurant 11
  {
    item_id: 41,
    restaurant_id: 11,
    name: "Chocolate Cake",
    price: 180,
    description: "Rich chocolate layer cake",
    image: "/chocolate-cake.jpg",
    category: "Cakes",
  },
  {
    item_id: 42,
    restaurant_id: 11,
    name: "Croissant",
    price: 90,
    description: "Buttery flaky pastry",
    image: "/croissant.jpg",
    category: "Pastries",
  },
  {
    item_id: 43,
    restaurant_id: 11,
    name: "Cupcakes",
    price: 60,
    description: "Assorted flavored cupcakes",
    image: "/cupcakes.jpg",
    category: "Cakes",
  },
  {
    item_id: 44,
    restaurant_id: 11,
    name: "Donuts",
    price: 50,
    description: "Glazed ring donuts",
    image: "/donuts.jpg",
    category: "Pastries",
  },

  // Mediterranean Delight (Mediterranean) - Restaurant 12
  {
    item_id: 45,
    restaurant_id: 12,
    name: "Falafel Wrap",
    price: 180,
    description: "Chickpea fritters in pita bread",
    image: "/falafel-wrap.jpg",
    category: "Wraps",
  },
  {
    item_id: 46,
    restaurant_id: 12,
    name: "Hummus Platter",
    price: 220,
    description: "Chickpea dip with pita bread",
    image: "/hummus-platter.jpg",
    category: "Appetizer",
  },
  {
    item_id: 47,
    restaurant_id: 12,
    name: "Greek Salad",
    price: 200,
    description: "Fresh vegetables with feta cheese",
    image: "/greek-salad.jpg",
    category: "Salad",
  },
  {
    item_id: 48,
    restaurant_id: 12,
    name: "Baklava",
    price: 140,
    description: "Sweet pastry with nuts and honey",
    image: "/baklava.jpg",
    category: "Dessert",
  },
]

export const mockCustomer: Customer = {
  customer_id: 1,
  name: "John Doe",
  email: "john.doe@example.com",
  phone: "+91 98765-43210",
  address: "House No. 123, Sector 15-D, Chandigarh, 160015",
}

export const mockDeliveryPersons: DeliveryPerson[] = [
  { delivery_id: 1, name: "Rajesh Kumar", phone: "+91 98765-11001" },
  { delivery_id: 2, name: "Priya Sharma", phone: "+91 98765-11002" },
  { delivery_id: 3, name: "Amit Singh", phone: "+91 98765-11003" },
]

// Mock orders will be stored in localStorage
export const getOrders = (): Order[] => {
  if (typeof window === "undefined") return []
  const orders = localStorage.getItem("orders")
  return orders ? JSON.parse(orders) : []
}

export const saveOrder = (order: Order) => {
  const orders = getOrders()
  orders.push(order)
  localStorage.setItem("orders", JSON.stringify(orders))
}
